In [1]:
import pandas as pd
data = pd.read_excel('WHO-data.xls')
data.head()

   ID  LOW  AGE  LWT  RACE  SMOKE  PTL  HT  UI  FTV   BWT
0   1    0   19  182     2      0    0   0   1    0  2523
1   2    0   33  155     3      0    0   0   0    3  2551
2   3    0   20  105     1      1    0   0   0    1  2557
3   4    0   21  108     1      1    0   0   1    2  2594
4   5    0   18  107     1      1    0   0   1    0  2600